version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
      - /etc/apache2/sites-available/000-default.conf :/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      backend:
        aliases:
          - laravel-app

  # mysql-db:
  #   image: mysql:5.7
  #   container_name: mysql-db
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=securerootpassword
  #     - MYSQL_DATABASE=${DB_DATABASE}
  #     - MYSQL_USER=${DB_USERNAME}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #   networks:
  #     backend:
  #       aliases:
  #         - db

networks:
  backend:
    name: backend-network